version: "3.8"

services:
  mkdocs:
    restart: always
    container_name: mkdocs
    build:
      dockerfile: Dockerfile
      context: ./Documentation
    ports:
      - "9000:8000"
    volumes:
      - ./Documentation:/app

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./Nginx
    container_name: nginx
    depends_on:
      - client
      - server
    networks:
      - backend
      - frontend
    ports:
      - "8000:80"
      - "8443:443"
    volumes:
      - ./Nginx/server.crt:/etc/nginx/server.crt
      - ./Nginx/server.key:/etc/nginx/server.key

  client:
    build:
      context: ./Client
    container_name: client
    networks:
      - frontend
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - NEXT_PUBLIC_DOCKER=${NEXT_PUBLIC_DEVELOPMENT_DOCKER}
    env_file:
      - ./Client/.env
    volumes:
      - ./Client:/app

  server:
    build:
      context: ./Server
    container_name: server

    networks:
      - backend
      - frontend
    ports:
      - "4000:4000"
    depends_on:
      - mongo
      - redis
    environment:
      - NODE_ENV2=${ENVIRONMENT}
    env_file:
      - ./Server/.env
    volumes:
      - ./Server:/app

  redis:
    image: redis:latest
    # image: redislabs/redismod
    container_name: redis
    networks:
      - backend
    ports:
      - "6379:6379"
    command: redis-server

  # Monitoring GUI
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - "8001:8001"
    networks:
      - backend
    user: root
    volumes:
      - ~/docker/BlueberryShop/RedisInsight:/db

  mongo:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    networks:
      - backend
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: root-db
    volumes:
      - ./Mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ~/docker/BlueberryShop/Mongo:/data/db

  # ===========================================================================================================================

networks:
  backend:
  frontend:
