env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'airbnb'

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
  - "prettier"
rules: {
     "quotes": ["error", "double"],
     "no-unused-vars":"warn",
     "no-console":"off"
}
