env:
  browser: true
  es2021: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "airbnb-base"

parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - "@typescript-eslint"
  - "prettier"
rules: {
    "quotes": ["error", "double"],
    "no-unused-vars":"warn",
    "no-console":"off",
    "linebreak-style": 0,
    "import/prefer-default-export": "off",
    "class-methods-use-this": "off",
    "no-underscore-dangle": "off",
    "no-shadow":"off",
    "object-curly-newline": 0,

    # Eslint
    "arrow-body-style": "off",
    "import/no-mutable-exports": "off",
    "max-len": [2, 120, 4],
    "no-case-declarations": "off",
    "radix": "off",


    # Typescript
    "@typescript-eslint/explicit-module-boundary-types": "off",

    "import/order": 0,
    "import/extensions": 0,
    "import/no-unresolved": [0,{ caseSensitive: false }],
    # "import/extensions": ["error", "ignorePackages", {
    #   "ts": "never",
    #   "tsx": "never",
    #   "js": "never",
    #   "jsx": "never",
    # }]
}

# settings: {
#   import/resolver:{
#     typescript:{}
#   }
# }

